#!/bin/sh

# The clickable help menu. Middle click to restart wm.

# If dwm is running, use dwm's readme and restart.
pidof dwm >/dev/null &&
	READMEFILE=/home/rishav/src/dwm/help.md
	restartwm() { pkill -HUP dwm ;} ||
		restartwm() { i3 restart ;}

case $BLOCK_BUTTON in
	1) alacritty -e  nvim "${READMEFILE:-${XDG_DATA_HOME:-$HOME/.local/share/help}/dwm.md}" ;;
	2) restartwm ;;
	3) notify-send "❓ Help module" "\- Left click to open guide.
- Middle click to refresh window manager." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac; echo "❓"
